name: Acceptance Stage

on: ['push']

jobs:
  e2e:
    runs-on: ubuntu-latest

    container: node:14-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Server and E2E Tests
        run: npm run start & npm run test:acceptance:e2e:dev