name: Acceptance Stage

on: ['push']

jobs:
  unit-and-integration:
    runs-on: ubuntu-latest

    container: node:15-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Unit, Integration Tests and Collect Code Coverage
        run: npm run test:ci

  e2e:
    runs-on: ubuntu-latest

    container: node:15-alpine

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run Server and E2E Tests
        run: npm run start & npm run test:acceptance:e2e:dev